Repository CodeChain-io/foundry, pull requests merged in 2020-04, with the labels that each got.

#298 Refactor TestHelper for states
  state/src/impls/test_helper.rs
  state/src/impls/top_level.rs
Labels: refactoring

#302 Remove unused errors
  core/src/consensus/mod.rs
  key/src/error.rs
  keystore/src/error.rs
Labels: refactoring

#301 Remove CodeChainMachine
  core/src/client/importer.rs
  core/src/codechain_machine.rs
  core/src/consensus/mod.rs
  core/src/consensus/null_engine/mod.rs
  core/src/consensus/solo/mod.rs
  core/src/consensus/tendermint/engine.rs
  core/src/consensus/tendermint/mod.rs
  core/src/lib.rs
  core/src/miner/miner.rs
  core/src/scheme/scheme.rs
  core/src/verification/canon_verifier.rs
  core/src/verification/mod.rs
  core/src/verification/noop_verifier.rs
  core/src/verification/verification.rs
  core/src/verification/verifier.rs
Labels: refactoring

#307 Fix bugs in the top level state and global cache
  state/src/cache/global_cache.rs
  state/src/cache/top_cache.rs
  state/src/impls/top_level.rs
Labels: bug

#325 Use `ctypes::Header` instead of `encoded::Header` in HeaderDownloader
  sync/src/block/downloader/header.rs
  sync/src/block/extension.rs
Labels: refactoring

#327 Remove deprecated comment about static validator
  core/src/block.rs
Labels: documentation

#290 Implement MemPoolAccess as a part of the context
  coordinator/src/context.rs
  core/src/client/client.rs
Labels: do-not-merge

#359 Remove explicit argument 'storage_id' from SubStorageAccess trait
  coordinator/src/context.rs
  coordinator/src/lib.rs
  coordinator/src/test_coordinator.rs
  coordinator/src/traits.rs
  state/src/impls/top_level.rs
Labels: mold
