Repository CodeChain-io/foundry, pull requests merged in 2020-03, with the labels that each got.

#239 Read term seconds from the common params of parent term
  core/src/consensus/tendermint/engine.rs
Labels: bug

#237 Fit test framework types into foundry-keystore
  test/package.json
  test/src/sdk/key/KeyStore.ts
  test/src/sdk/key/LocalKeyStore.ts
  test/src/sdk/key/MemoryKeyStore.ts
  test/src/sdk/key/RemoteKeyStore.ts
  test/src/sdk/key/__test__/LocalKeyStore.spec.ts
  test/src/sdk/key/__test__/MemoryKeyStore.spec.ts
  test/src/sdk/key/index.ts
  test/yarn.lock
Labels: crypto

#262 Merge ClosedBlock and LockedBlock into one
  core/src/block.rs
  core/src/client/client.rs
  core/src/client/importer.rs
  core/src/client/mod.rs
  core/src/client/test_client.rs
  core/src/consensus/solo/mod.rs
  core/src/miner/miner.rs
Labels: refactoring

#266 Add "Running an IBC scenario" section in the ibc.ts/README.md
  ibc.ts/README.md
Labels: documentation, experiment, ics

#251 Refactor the state/cache module
  state/src/cache/global_cache.rs
  state/src/cache/lru_cache.rs
  state/src/cache/shard_cache.rs
  state/src/cache/top_cache.rs
  state/src/cache/write_back.rs
Labels: refactoring

#273 Do not export ClientState to channel
  core/src/ibc/channel_04/manager.rs
  core/src/ibc/client_02/manager.rs
Labels: experiment, ics

#256 Remove omitted field from ImportRoute
  core/src/blockchain/blockchain.rs
  core/src/blockchain/mod.rs
  core/src/blockchain/route.rs
  core/src/blockchain/update_result.rs
  core/src/client/importer.rs
Labels: refactoring

#270 Fix a wrong argument name
  core/src/blockchain/body_db.rs
Labels: refactoring

#282 Remove ChainNotify::transactions_received()
  core/src/client/chain_notify.rs
  core/src/client/client.rs
  core/src/client/mod.rs
  core/src/client/test_client.rs
  core/src/service.rs
  sync/src/transaction/extension.rs
Labels: refactoring
