Repository CodeChain-io/foundry, pull requests merged in 2020-01, with the labels that each got.

#89 Convert constants to discriminated enum
  core/src/consensus/stake/actions.rs
  core/src/consensus/tendermint/message.rs
  sync/src/block/message/mod.rs
  sync/src/block/message/request.rs
  sync/src/block/message/response.rs
  types/src/errors/history_error.rs
  types/src/errors/runtime_error.rs
  types/src/errors/syntax_error.rs
  types/src/transaction/shard.rs
  vm/src/decoder.rs
  vm/src/executor.rs
  vm/src/instruction.rs
  vm/src/lib.rs
  vm/tests/executor.rs
Labels: refactoring

#91 Correct a mistake that was made while reading the mem-pool-fee-bump-shift configuration
  foundry/config/mod.rs
Labels: bug

#102 Fix typoes on the comment
  core/src/error.rs
  core/src/verification/verifier.rs
Labels: documentation

#108 Update the logic to check whether the block contains transactions
  sync/src/block/downloader/body.rs
  sync/src/block/extension.rs
  types/src/header.rs
Labels: bug

#110 Change foundry to Foundry in README.md
  README.md
Labels: documentation

#104 Do not prohibit headers whose body is malformed
  core/src/verification/queue/mod.rs
Labels: bug

#128 Rename CodeChain to Foundry in the ibc directory
  core/src/ibc/client_02/foundry/mod.rs
  core/src/ibc/client_02/foundry/types.rs
  core/src/ibc/client_02/mod.rs
  core/src/ibc/client_02/types.rs
  core/src/ibc/custom_action_handler/mod.rs
Labels: ics
