Repository CodeChain-io/foundry, pull requests merged in 2020-06, with the labels that each got.

#411 Reduce lock region
  core/src/miner/miner.rs
Labels: refactoring

#418 Fetch consistent state in mempool functions
  core/src/client/test_client.rs
  core/src/miner/mem_pool.rs
  core/src/miner/miner.rs
  core/src/miner/mod.rs
Labels: bug

#419 Fix bug in the pay tx
  basic_module/account/src/impls.rs
Labels: bug

#421 Change the mutability of SubStorageAccess
  basic_module/staking/src/execute.rs
  coordinator/src/context/sub_storage_access.rs
Labels: refactoring

#416 Update the specification of Foundry address scheme
  spec/CodeChain-Address.md
  spec/Foundry-Address.md
  spec/JSON-RPC.md
  spec/README.md
  spec/Staking.md
Labels: documentation
