Repository CodeChain-io/foundry, pull requests merged in 2020-02, with the labels that each got.

#115 Re-send a body request when the body is corrupted
  sync/src/block/downloader/body.rs
  sync/src/block/extension.rs
Labels: bug

#136 Change constants to enumerations
  state/src/item/account.rs
  state/src/item/dummy_shard_text.rs
  state/src/item/metadata.rs
  state/src/item/mod.rs
  state/src/item/regular_account.rs
  state/src/item/shard.rs
  types/src/transaction/action.rs
Labels: refactoring

#161 Rename Action to Datagram in IBC code
  core/src/ibc/transaction_handler/datagrams.rs
  core/src/ibc/transaction_handler/mod.rs
Labels: ics

#171 Bug fix in on_request_commit_message method
  core/src/consensus/tendermint/worker.rs
Labels: bug

#116 Refactor BodyDownloader
  sync/src/block/downloader/body.rs
  sync/src/block/extension.rs
Labels: refactoring

#170 Add get_current_height function to the IBC Context
  core/src/client/client.rs
  core/src/ibc/context.rs
  core/src/ibc/transaction_handler/mod.rs
  rpc/src/v1/impls/ibc.rs
  state/src/ibc.rs
  state/src/impls/top_level.rs
Labels: ics

#166 Implement connOpenTry datagram in the ICS connection spec
  core/src/ibc/connection_03/manager.rs
  core/src/ibc/connection_03/types.rs
  core/src/ibc/transaction_handler/datagrams.rs
  core/src/ibc/transaction_handler/mod.rs
Labels: ics

#178 Extract a context variable in the IBC transaction handler
  core/src/ibc/transaction_handler/mod.rs
Labels: ics

#179 Add context field to `Manager`s in the IBC code
  core/src/ibc/client_02/manager.rs
  core/src/ibc/connection_03/manager.rs
  core/src/ibc/transaction_handler/mod.rs
  rpc/src/v1/impls/ibc.rs
Labels: ics

#181 Report double votes in commit messages.
  core/src/consensus/tendermint/worker.rs
Labels: bug

#190 Return error when importing not allowed transactions
  core/src/miner/miner.rs
Labels: bug

#180 Implement ConnOpenAck datagrain in the ICS Connection spec
  core/src/ibc/connection_03/manager.rs
  core/src/ibc/transaction_handler/datagrams.rs
  core/src/ibc/transaction_handler/mod.rs
Labels: ics
